language: go

go:
  - master

addons:
  apt:
    packages:
      - python-pygments
      
install:
  - go get github.com/spf13/hugo
  - rm -rf public || exit 0

script:
  - hugo --theme=hemingway
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master