addons:
  apt:
    packages:
      - python-pygments
      
install:
  - wget $HUGO_BINARY_URL
  - sudo dpkg -i $HUGO_BINARY_NAME_AFTER_DOWNLOAD
  - rm -rf public || exit 0

script:
  - hugo
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master